// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Web.Models;

namespace Movies.Web.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20211025124716_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movies.Web.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DirectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorId = 6,
                            ReleaseDate = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Force Awakens"
                        },
                        new
                        {
                            MovieId = 2,
                            ReleaseDate = new DateTime(2009, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek"
                        });
                });

            modelBuilder.Entity("Movies.Web.Models.MovieActor", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            PersonId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            MovieId = 2
                        });
                });

            modelBuilder.Entity("Movies.Web.Models.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            Title = "British"
                        },
                        new
                        {
                            NationalityId = 2,
                            Title = "French"
                        },
                        new
                        {
                            NationalityId = 3,
                            Title = "American"
                        });
                });

            modelBuilder.Entity("Movies.Web.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("NationalityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Birthday = new DateTime(2021, 10, 25, 13, 47, 15, 584, DateTimeKind.Local).AddTicks(5951),
                            FirstName = "Larry",
                            LastName = "Losser",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            Birthday = new DateTime(1970, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Simon",
                            LastName = "Pegg",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 3,
                            Birthday = new DateTime(1976, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benedict",
                            LastName = "Cumberbatch",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 4,
                            Birthday = new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            LastName = "Reno",
                            NationalityId = 2
                        },
                        new
                        {
                            PersonId = 5,
                            Birthday = new DateTime(1980, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chris",
                            LastName = "Pine",
                            NationalityId = 3
                        },
                        new
                        {
                            PersonId = 6,
                            Birthday = new DateTime(1966, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "JJ",
                            LastName = "Abrams",
                            NationalityId = 3
                        });
                });

            modelBuilder.Entity("Movies.Web.Models.Movie", b =>
                {
                    b.HasOne("Movies.Web.Models.Person", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Movies.Web.Models.MovieActor", b =>
                {
                    b.HasOne("Movies.Web.Models.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Web.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Web.Models.Person", b =>
                {
                    b.HasOne("Movies.Web.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
